meetup/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views

app_name = 'meetup'
urlpatterns = [
    url(r'^$', views.IndexPageView.as_view(), name='index'),
    url(r'^register/$', views.RegisterPage.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^(?P<pk>[0-9]+)/$', views.GroupView.as_view(), name='group'),
    url(r'^create-meetup/$', views.CreateMeetup.as_view(), name='create_meetup'),
    url(r'^profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^group-details/(?P<pk>[0-9]+)$', views.GroupDetails.as_view(), name='group_details'),
]

meetup/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)


class Category(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category


class Group(models.Model):
    name = models.CharField(max_length=200)
    group_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    group_description = models.TextField()

    def __str__(self):
        return self.name

#
# class Membership(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     group = models.ForeignKey(Group, on_delete=models.CASCADE)


class Meetup(models.Model):
    meetup_group = models.ForeignKey(Group, on_delete=models.CASCADE)
    meetup_date_time = models.DateTimeField('date of meetup')
    meetup_place = models.CharField(max_length=200)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                   null=True, blank=True)

    class Meta:
        ordering = ['-meetup_date_time']

meetup/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from meetup.models import Meetup
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, ButtonHolder

# CATEGORIES = [
#     ('Tech', 'Tech'),
#     ('Music', 'Music'),
#     ('Writing', 'Writing'),
#     ('Photography', 'Photography'),
#     ('Learning', 'Learning'),
#     ('Sports', 'Sports'),
#     ('Food and Drink', 'Food and Drink'),
#     ('Dance', 'Dance'),
# ]


class SignUpForm(UserCreationForm):

    email = forms.EmailField(required=True, max_length=254,
                             help_text='Required. Enter a valid email address.')

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('signup', 'Sign up', css_class='btn-primary'))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

        def save(self, commit=True):
            user = super(self, UserCreationForm).save(commit=False)
            user.set_password(self.cleaned_data["password1"])
            if commit:
                user.save()
            return user


class CreateMeetupForm(forms.ModelForm):

    meetup_date_time = forms.DateTimeField(input_formats=["%d/%m/%Y %H:%M"],
                                           required=True,
                                           help_text="DD/MM/YYYY HH:MM 24-hour "
                                                     "format")

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('create_meetup', 'Create', css_class='btn-primary'))

    class Meta:
        model = Meetup
        fields = ('meetup_group', 'meetup_place', 'meetup_date_time')


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'GET'
        self.helper.layout = Layout(
            'username',
            'password',
            ButtonHolder(
                Submit('login', 'Login', css_class='btn-primary')
            )
        )

meetup/views.py
# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import TemplateView, CreateView, FormView, DetailView
from django.contrib.auth import authenticate, login, logout, forms
from meetup.forms import SignUpForm, CreateMeetupForm, LoginForm
from django.shortcuts import render, redirect, render_to_response
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from .models import Category, Meetup, Group, User


class IndexPageView(TemplateView):
    template_name = 'index.html'
    category_list = Category.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexPageView, self).get_context_data(**kwargs)
        context['categories'] = self.category_list
        return context


class LoginView(FormView):
    form_class = LoginForm
    success_url = '/profile/'
    template_name = 'registration/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)


# class LoginView(FormView):
#     form_class = LoginForm
#     success_url = reverse_lazy('')
#     template_name = 'registration/login.html'
#
#     def post(self, request, *args, **kwargs):
#         if request.method == 'POST':
#             form = forms.AuthenticationForm(data=request.POST)
#             if form.is_valid():
#                 user = form.get_user()
#                 login(request, user)
#                 return HttpResponseRedirect("/profile/")
#         else:
#             form = forms.AuthenticationForm()
#         return render(request, 'registration/login.html', {'form': form})


class RegisterPage(CreateView):
    form_class = SignUpForm
    template_name = 'register.html'

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                email = form.cleaned_data['email']
                raw_password = form.cleaned_data['password1']
                m = User(username=username, email=email,
                         password=raw_password, is_staff=True)
                m.save()
                login(request, m)
                return HttpResponseRedirect("/profile/")

        else:
            form = SignUpForm()

        return render(request, 'register.html', {'form': form})


class GroupView(DetailView):
    model = Category
    template_name = 'group.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GroupView, self).get_context_data(**kwargs)
        context['group_list'] = Group.objects.all()
        return context


class CreateMeetup(CreateView):
    form_class = CreateMeetupForm
    template_name = "create_meetup.html"
    cat = Category.objects.all()

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = CreateMeetupForm(request.POST)
            if form.is_valid():
                group = form.cleaned_data['meetup_group']
                place = form.cleaned_data['meetup_place']
                date = form.cleaned_data['meetup_date']
                m = Meetup(meetup_group=group, meetup_place=place,
                           meetup_date=date)
                m.save()
                return HttpResponse("Meetup created successfully")

        else:
            form = CreateMeetupForm()

        return render(request, 'create_meetup.html', {'form': form})


class UserProfileView(TemplateView):
    template_name = 'profile.html'
    groups_list = Group.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['groups'] = self.groups_list
        return context


class GroupDetails(DetailView):
    model = Group
    template_name = 'group_details.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GroupDetails, self).get_context_data(**kwargs)
        context['meetup_list'] = Meetup.objects.all()
        return context

meetup/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Meetup{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

meetup/templates/category.html
{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

{% if category_list %}
    <ul>
    {% for category in category_list %}
        <li><a href="{% url 'polls:detail' question.id %}" class="btn btn-info" role="button">{{ question.question_text }}</a></li>
       
    {% endfor %}

    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

meetup/templates/create_meetup.html
{% load static crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<style>
 body, html {
  height: 130%;
     font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-img {
  /* The image used */
  background-image: url({% static 'images/demo/backgrounds/login1.jpg' %});

  /* Control the height of the image */
  min-height: 380px;

  /* Center and scale the image nicely */
    width: 100%;
    height: 70%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

/* Add styles to the form container */
.container {
    position: absolute;
    right: 40%;
    margin: 40px;
    max-width: 400px;
    padding: 16px;
}

/* Full-width input fields */
  input[type=text], input[type=password] {
  width: 80%;
  right: 40%;
  margin: 20px;
  max-width: 300px;
  padding: 16px;
  border: aqua;
  background: #f1f1f1;
}


/* Set a style for the submit button */
.btn {
    position: center;
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  width: 80%;
  right: 40%;
}


</style>
    <link href="{% static 'layout/styles/layout.css'%}" rel="stylesheet" type="text/css" media="all">
</head>


<body>
{% block content %}
<div class="bg-img">
<div class="container">
    {% if user.is_authenticated %}

  <form method="GET">
    {% csrf_token %}
        {% crispy form %}
  </form>

    {% else %}

    <p>You need to login first. </p>
    <a class="btn btn-info" href="/login/">Login</a>

    <p> Not registered? </p>
    <a class="btn btn-info" href="/register/">Sign up</a>
    {% endif %}
</div>
</div>
{% endblock %}
</body>
</html>

meetup/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forgot Password</title>

</head>
<body>
	<div class="limiter">
		<div class="container-login100" >
			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
				<form class="login100-form validate-form flex-sb flex-w">
					<span class="login100-form-title p-b-53">
						Sign up with
					</span>

					<a href="https://www.facebook.com/" class="btn-face m-b-20">
						<i class="fa fa-facebook-official"></i>
						Facebook
					</a>

					<a href="https://accounts.google.com/signin/v2/identifier?hl=en&passive=true&continue=https%3A%2F%2Fwww.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin" class="btn-google m-b-20">
						<img src="images/icons/icon-google.png" alt="GOOGLE">
						Google
					</a>

                    <div class="p-t-31 p-b-9">
						<span class="txt1">
							Your name
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Name is required">
						<input class="input100" type="text" name="name" >
						<span class="focus-input100"></span>
					</div>

                    <div class="p-t-31 p-b-9">
						<span class="txt1">
							E-mail address
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Username is required">
						<input class="input100" type="text" name="username" >
						<span class="focus-input100"></span>
					</div>

					<div class="p-t-13 p-b-9">
						<span class="txt1">
							Password
						</span>


					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" >
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Sign In
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</body>
</html>

meetup/templates/group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meetups</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<h1>{{ category }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% for group in group_list %}
    {% if category.id == group.group_category_id %}
        <li><a class="btn btn-info" role="button" href="{% url 'meetup:group_details' group.id  %}">{{ group.name}} </a></li>
    {% endif %}
{% endfor %}
</body>
</html>

meetup/templates/group_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h3> Meetups </h3>
<table>
{% for meetup in meetup_list %}
    {% if meetup.meetup_group_id == group.id %}
        <tr>
            <td>{{ meetup.meetup_group }} {{ meetup.meetup_date }} {{ meetup.meetup_place }}</td>
        </tr>
    {% endif %}
{% endfor %}
</table>
<h3> Description </h3>
{{ group.group_description }}
</body>
</html>

meetup/templates/home.html
{% extends "base.html" %}
{% load static %}
<html>
<head>
<title>Meetup</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<style>
    .centered {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
.container {
    position: relative;
    max-width: 800px; /* Maximum width */
    margin: 0 auto; /* Center it */
}

.container .content {
    position: absolute; /* Position the background text */
    bottom: 0; /* At the bottom. Use top:0 to append it to the top */
    background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
    color: #f1f1f1; /* Grey text */
    width: 100%; /* Full width */
    padding: 20px; /* Some padding */
}
.container .content {
    position: absolute; /* Position the background text */
    bottom: 0; /* At the bottom. Use top:0 to append it to the top */
    background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
    color: #f1f1f1; /* Grey text */
    width: 100%; /* Full width */
}
.image {
  display: block;
  width: 100%;
  height: auto;
}


</style>
    <link href="{% static 'layout/styles/layout.css'%}" rel="stylesheet" type="text/css" media="all">
</head>
<body>
<div id="top">
<div class="wrapper row0">
  <div id="topbar" class="hoc clear">
    <div class="fl_left">
      <ul class="nospace">
          {% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
          {% else %}
        <li><a href=""><i class="fas fa-home fa-lg"></i></a></li>
        <li><a href="login/">Login</a></li>
        <li><a href="register/">Register</a></li>
          {% endif %}
      </ul>
    </div>
   </div>
</div>

<div class="wrapper row1">
  <header id="header" class="hoc clear">
    <div id="logo" class="one_quarter first">
      <h1><a href="">Meetup</a></h1>
     </div>
  </header>
</div>

{% block content %}
<div class="container">
  <div class="image" style="background-image: url({% static 'images/demo/backgrounds/Meetup1.jpg' %}); height: 70%; width:100%;" >
        <div class="content">
            <div class="center">
        <h3 >What do you love?</h3>
        <h3 >Do more of it at Meetup</h3>
        <footer><a class="btn" href="create_meetup/">Create a Meetup</a></footer>
        </div>
        </div>
      </div>
  </div>
    </div>
{% endblock %}

<div class="wrapper row3">
    <main class="row firstinfo">
        <article>
            <h1 class="heading">Explore by category</h1>
                {% if category %}
                    <ul>
                        {% for cat in category %}
                            <div class="row">
                                <li><a href="{{ cat.id }}" class="btn btn-info" style="background-image:url('{% static 'images/demo/backgrounds/category_{{ forloop.counter }}.jpg' %}');" role="button">{{ cat.category }} </a></li>
                            </div>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No categories are available.</p>
                {% endif %}
        </article>
            <div class="clear"></div>
    </main>
</div>

</body>
</html>

meetup/templates/index.html
{% load static %}

<head>
<title>Meetup</title>
<meta charset="utf-8">
    		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
		<script src="{% static 'js/skel.min.js' %}"></script>
		<script src="{% static 'js/skel-layers.min.js' %}"></script>
		<script src="{% static 'js/init.js' %}"></script>
	<!--
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE
	DESIGNED & DEVELOPED by FreeHTML5.co

	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->
	<!-- <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet"> -->

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<script src="js/respond.min.js"></script>
		<noscript>
			<link rel="stylesheet" href="{% static 'css/skel.css' %}" />
			<link rel="stylesheet" href="{% static 'css/style.css' %}" />
			<link rel="stylesheet" href="{% static 'css/style-wide.css' %}" />
		</noscript>

<style>
    .centered {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
.container {
    position: relative;
    height: 100%; /* Maximum width */
    margin: 0 auto; /* Center it */
}

.container .content {
    position: absolute; /* Position the background text */
    bottom: 0; /* At the bottom. Use top:0 to append it to the top */
    background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
    color: #f1f1f1; /* Grey text */
    width: 100%; /* Full width */
}
.image {
  display: block;
  width: 100%;
  height: auto;
}
.row {
  display: flex;
  flex-wrap: wrap;
  padding: 0 4px;
}

/* Create four equal columns that sits next to each other */
.column {
  flex: 25%;
  max-width: 25%;
  padding: 0 4px;
}

.column img {
  margin-top: 8px;
  vertical-align: middle;
}

/* Responsive layout - makes a two column-layout instead of four columns */
@media screen and (max-width: 800px) {
  .column {
    flex: 50%;
    max-width: 50%;
  }
}

/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column {
    flex: 100%;
    max-width: 100%;
  }
}
</style>
    <link href="{% static 'layout/styles/layout.css'%}" rel="stylesheet" >
</head>
    <body>
        <div id="top">
            <div class="wrapper row0">
                <div id="topbar" class="hoc clear">
                    <div class="fl_right">
                        <ul class="nospace">
                            {% if user.is_authenticated %}
                                Hi {{ user.username }}!
                                <p><a href="{% url 'logout' %}">logout</a></p>
                            {% else %}
                                <li><a href="{% url 'login' %}">Login</a></li>
                                <li><a href="{% url 'meetup:register' %}">Sign up</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="wrapper row1">
            <header id="header" class="hoc clear">
                <div id="logo" >
                    <h1 href="">Meetup</h1>
                </div>
            </header>
        </div>
        {% block content %}
            <div class="container">
                <div class="image" style="background-image: url({% static 'images/demo/backgrounds/background.png' %}); height: 70%; width:100%;" >
                    <div class="center">
                        <div class="centered">
                            <h3 >What do you love?</h3>
                            <h3 >Do more of it at Meetup</h3>
                            {% if user.is_authenticated %}
                                <a class="btn btn-info" href="{% url 'meetup:create_meetup' %}">Create a Meetup</a>
                            {% else %}
                                <a class="btn" href="{% url 'meetup:register' %}">Sign up</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}

{##}
{#        <div class="wrapper row3">#}
{#            <main class="row firstinfo">#}
{#                 <article>#}
{#                     <h1 class="heading">Explore by category</h1>#}
{#                         {% if categories %}#}
{#                             <ul>#}
{#                                 {% for category_name in categories %}#}
{#                                     <div class="btn-group">#}
{#                                         <li><a href="{% url 'meetup:meetup' category_name.id  %}" class="btn btn-info" style="background-image:url('{% static 'images/demo/backgrounds/{{ category_name }}.jpg' %}');" role="button">{{ category_name.category }} </a></li>#}
{#                                     </div>#}
{#                                 {% endfor %}#}
{#                             </ul>#}
{#                         {% else %}#}
{#                            <p>No categories are available.</p>#}
{#                         {% endif %}#}
{#                </article>#}
{#                <div class="clear"></div>#}
{#            </main>#}
{#        </div>#}
{##}

        <div id="extra">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 text-center animate-box">
                        <a class="work" href="1/">
                            <div class="work-grid" href="{% url 'meetup:group' 1 %}"><img src='{% static 'images/demo/backgrounds/tech.png' %}' alt="">
                                <div class="inner">
                                    <div class="desc">
                                        <h3>Tech</h3>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <a class="work" href="2/">
                            <div class="work-grid" href="{% url 'meetup:group' 2  %}"><img src='{% static 'images/demo/backgrounds/sports.png' %}' width="300px" height="200" alt="">
                                <div class="inner">
                                    <div class="desc">
                                        <h3>Sports</h3>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <a class="work" href="3/">
                            <div class="work-grid" href="{% url 'meetup:group' 3  %}"><img src='{% static 'images/demo/backgrounds/learning.png' %}' alt="">
                                <div class="inner">
                                    <div class="desc">
                                        <h3>Learning</h3>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <a class="work" href="4/">
                            <div class="work-grid" href="{% url 'meetup:group' 4  %}"><img src='{% static 'images/demo/backgrounds/photography.png' %}' alt="">
                                <div class="inner">
                                    <div class="desc">
                                        <h3>Photography</h3>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <a class="work" href="5/">
                            <div class="work-grid" href="{% url 'meetup:group' 5  %}"><img src='{% static 'images/demo/backgrounds/writing.png' %}' alt="">
                                <div class="inner">
                                    <div class="desc">
                                        <h3>Writing</h3>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <a class="work" href="6/">
                            <div class="work-grid" href="{% url 'meetup:group' 6  %}"><img src='{% static 'images/demo/backgrounds/music.png' %}' alt="">
                                <div class="inner">
                                    <div class="desc">
                                        <h3>Music</h3>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <a class="work" href="7/">
                            <div class="work-grid" href="{% url 'meetup:group' 7  %}"><img src='{% static 'images/demo/backgrounds/foodanddrink.png' %}' alt="">
                                <div class="inner">
                                    <div class="desc">
                                        <h3>Food and Drink</h3>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <a class="work" href="8/">
                            <div class="work-grid" href="{% url 'meetup:group' 8  %}"><img src='{% static 'images/demo/backgrounds/dance.png' %}' alt="">
                                <div class="inner">
                                    <div class="desc">
                                        <h3>Dance</h3>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        {% if user.is_authenticated %}
        {% else %}
            <div class="wrapper coloured">
                <section class="hoc container clear">
                    <div class="sectiontitle">
                        <h2>How Meetup works</h2>
                    </div>
                    <ul class="nospace group latest">
                        <li class="one_half first">
                            <article>
                                <div class="excerpt">
                                    <h2>Find a Meetup</h2>
                                    <p>Discover local Meetups for all the things you love.</p>
                                    <footer><a class="btn" href="{% url 'meetup:register' %}">Sign up</a></footer>
                                </div>
                            </article>
                        </li>
                        <li class="one_half">
                            <article>
                                <div class="excerpt">
                                    <h2 class="heading">Create a Meetup</h2>
                                    <p>Create your own Meetup, and draw from a community of millions.</p>
                                    <footer><a class="btn" href="{% url 'meetup:create_meetup' %}">Create a Meetup</a></footer>
                                </div>
                            </article>
                        </li>
                    </ul>
                </section>
            </div>
        {% endif %}
    </body>
</html>

meetup/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Profile</title>
</head>
<body>
{% if user.is_authenticated %}

    <h> Welcome to your Account {{ user.username }} ! </h>
    {% for groups_part_of in groups %}
        {% if groups.users == user %}
            <p>{{ groups_part_of }}</p>
        {% endif %}
    {% endfor %}
    <h2> Create a Meetup? </h2>
    <a class="btn btn-info" href="/create-meetup/">Create a Meetup</a>
{% endif %}
</body>
</html>